name: Python CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run linting
        run: |
          poetry run flake8 .
          poetry run isort --check .

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=gendiff --cov-report=lcov tests > coverage.lcov

      - name: List files in current directory
        run: ls -la

      - name: Install CodeClimate Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-reporter
          chmod +x ./cc-reporter

      - name: Before build - CodeClimate Reporter
        run: |
          ./cc-reporter before-build

      - name: Upload coverage to CodeClimate
        run: |
          ./cc-reporter after-build --exit-code $? --coverage-input-type lcov
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}